const String supbaseUrl = 'https://wdwhpfwwbvketavjtcei.supabase.co';
const String supbaseAnonKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indkd2hwZnd3YnZrZXRhdmp0Y2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzgxMTAsImV4cCI6MjA3MDMxNDExMH0.vwPmk-QSA5QajVIgQTiLknSYP0KmoKn6dJqu64mXO3I';
