// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnY39vCi3bqZTJ_3s93hsIaBEPJdqb9ls',
    appId: '1:897609149361:web:3a2a5431a7dd7813f5eb90',
    messagingSenderId: '897609149361',
    projectId: 'yumquiknotifiction',
    authDomain: 'yumquiknotifiction.firebaseapp.com',
    storageBucket: 'yumquiknotifiction.firebasestorage.app',
    measurementId: 'G-SZG9SRS1LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJDHm2jWG-9KyTqbbD-Li3ENd55LPco_Q',
    appId: '1:897609149361:android:4793a0937209f53cf5eb90',
    messagingSenderId: '897609149361',
    projectId: 'yumquiknotifiction',
    storageBucket: 'yumquiknotifiction.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_Bi_1UDwbHZTRIfY0wZDKnZjY8YaU98',
    appId: '1:897609149361:ios:8d263dc4485a1b7bf5eb90',
    messagingSenderId: '897609149361',
    projectId: 'yumquiknotifiction',
    storageBucket: 'yumquiknotifiction.firebasestorage.app',
    iosBundleId: 'com.example.yumquickdashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ_Bi_1UDwbHZTRIfY0wZDKnZjY8YaU98',
    appId: '1:897609149361:ios:8d263dc4485a1b7bf5eb90',
    messagingSenderId: '897609149361',
    projectId: 'yumquiknotifiction',
    storageBucket: 'yumquiknotifiction.firebasestorage.app',
    iosBundleId: 'com.example.yumquickdashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnY39vCi3bqZTJ_3s93hsIaBEPJdqb9ls',
    appId: '1:897609149361:web:80fa9cca7943e869f5eb90',
    messagingSenderId: '897609149361',
    projectId: 'yumquiknotifiction',
    authDomain: 'yumquiknotifiction.firebaseapp.com',
    storageBucket: 'yumquiknotifiction.firebasestorage.app',
    measurementId: 'G-2JPZZE6QE3',
  );
}
